ALTER TABLE MEMBER
ADD CONSTRAINT unique_num UNIQUE (phoneNumber);

ALTER TABLE EVENT
ADD FOREIGN KEY (organizerID) REFERENCES MEMBER(memberID) ON DELETE SET NULL;

ALTER TABLE MEMBER
ADD COLUMN age INT;

ALTER TABLE MEMBER
ALTER COLUMN isActive SET DEFAULT TRUE;

ALTER TABLE MEMBER
ALTER COLUMN memberID SET DATA TYPE SERIAL;


